# binop_separator = "Front"
# blank_lines_lower_bound = 0
# blank_lines_upper_bound = 1
# brace_style = "SameLineWhere"
# color = "Auto"
# combine_control_expr = true
comment_width = 100
condense_wildcard_suffixes = true
# control_brace_style = "AlwaysSameLine"
# disable_all_formatting = false
edition = "2018"
empty_item_single_line = false
# enum_discrim_align_threshold = 0
error_on_line_overflow = true
error_on_unformatted = true
# fn_args_layout = "Tall"
# fn_single_line = false
force_explicit_abi = false
# force_multiline_blocks = false
format_code_in_doc_comments = true
format_macro_matchers = true
# format_macro_bodies = true
# format_strings = false
# hard_tabs = false
# hide_parse_errors = false
# ignore = []
imports_granularity = "Crate"
# imports_indent = "Block"
imports_layout = "HorizontalVertical"
# indent_style = "Block"
# inline_attribute_width = 0
# license_template_path = ""
# match_arm_blocks = true
match_block_trailing_comma = true
max_width = 120
# merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
# remove_nested_parens = true
reorder_impl_items = true
# reorder_imports = true
# reorder_modules = true
# report_fixme = "Never"
# report_todo = "Never"
# required_version = "CARGO_PKG_VERSION"
# skip_children = false
# space_after_colon = true
# space_before_colon = false
spaces_around_ranges = true
# struct_field_align_threshold = 0
# struct_lit_single_line = true
# tab_spaces = 4
# trailing_comma = "Vertical"
# trailing_semicolon = true
# type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
# use_small_heuristics = "Max"
use_try_shorthand = true
version = "Two"
# where_single_line = false
wrap_comments = true
