name: Bump version Develop

on:
  push:
    branches:
      - develop

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen then deploy"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: '${{ secrets.GH_TOKEN }}'
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.16.3
        with:
          prerelease: 'prerelease'
          branch: 'develop'
          github_token: '${{ secrets.GH_TOKEN }}'
          dry_run: true
